### ISSUE TITLE
<loc> paths with RealUrl 2.0 / typo3 8.4.1

### ISSUE THREAD

**Issue by nwMarcS** [beardcoder/sitemap_generator#28]
hy,

did you tested it with the above configuration? the urls at the sitemap will be like

<loc>http://xxx.test.com/index.php?id=2</loc>

instead of

<loc>http://xxx.test.com/overview</loc>

which is working in a simple menu.

(the filename generation for sitemap.xml and sitemap_news.xml within the RealUrl configuration is working well)

**Comment by markussom** [comment]
Hello I don't understand your question. Which above configuration?

**Comment by nwMarcS** [comment]
hy markus,

here is a live example:

http://dev8.netserver17.at/sitemap.xml >> eg "<loc>http://dev8.netserver17.at/index.php?id=1</loc>"

but realurl 2.1.5. is enabled and a simple menu like here: http://dev8.netserver17.at/ is working fine ...

somehow the extension doesn´t find the correct realurls

hangloose

marc

**Comment by markussom** [comment]
Good morning, sorry for the late answer,

is this resolved or an existing bug?

**Comment by nwMarcS** [comment]
Hallo Markus,

wir haben das 8.4.1 nicht mehr im Einsatz – und beim 8.7.1 noch nicht getestet – werde es aber noch dort testen und geb dir Bescheid ;)

SG

Marco

Von: Markus Sommer [mailto:notifications@github.com]
Gesendet: Mittwoch, 03. Mai 2017 10:20
An: markussom/sitemap_generator <sitemap_generator@noreply.github.com>
Cc: Marco Schrittwieser <m.schrittwieser@netwerk.at>; Author <author@noreply.github.com>
Betreff: Re: [markussom/sitemap_generator] <loc> paths with RealUrl 2.0 / typo3 8.4.1 (#28)


Good morning, sorry for the late answer,

is this resolved or an existing bug?

**Comment by markussom** [comment]
Vielen dank für die Info :) mit der 8.7 habe ich momentan noch meine Probleme aufgrund des Testing Frameworks.
Manuell getestet ist sie und es läuft auch einwandfrei bis auf die Google News Sitemap.

Danke und liebe Grüße
Markus
